# Generated by Django 6.0.5 on 2026-06-26 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Couleur')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Carburant')),
            ],
        ),
        migrations.CreateModel(
            name='Gearboxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Boite de vitesse')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Option')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.category', verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Motorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Motorisation')),
                ('fuel', models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.fuel', verbose_name='Carburant')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('registration', models.CharField(max_length=9, unique=True, verbose_name='Immatriculation')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300000)], verbose_name='Kilométrage')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2011), django.core.validators.MaxValueValidator(2026)], verbose_name='Année')),
                ('door', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Nombre de portes')),
                ('place', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)], verbose_name='Nombre de places')),
                ('first_registration', models.DateField(verbose_name='Mise en circulation')),
                ('din_power', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Puissance DIN')),
                ('tax_horsepower', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puissance fiscale')),
                ('photo', models.ImageField(upload_to='cars', verbose_name='Photo')),
                ('selling_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(100000)], verbose_name='Prix de vente')),
                ('is_forsale', models.BooleanField(default=True, verbose_name='En vente')),
                ('rental_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='Tarif location')),
                ('is_forrent', models.BooleanField(default=True, verbose_name='En location')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.color', verbose_name='Couleur')),
                ('gearboxe', models.ForeignKey(blank=True, max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.gearboxe', verbose_name='Boite de vitesse')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model', verbose_name='Modèle')),
                ('motorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.motorization', verbose_name='Motorisation')),
                ('option', models.ManyToManyField(to='cars.option', verbose_name='Options')),
            ],
        ),
    ]
